language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
branches:
  only:
    - master
    - staging
services:
  - postgresql
  - redis-server
before_script:
  - psql -c "CREATE DATABASE ase_acecard_test_database;" -U postgres
  - psql -c "CREATE USER acecard WITH PASSWORD 'acecard';" -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO acecard;' -U postgres
  - psql -d  ase_acecard_test_database -a -f sql/setup-database.sql
  - psql -d  ase_acecard_test_database -a -f sql/insert-database.sql
