language: java
jdk:
  - openjdk11
before_install:
  - chmod +x mvnw
branches:
  only:
    - master
    - staging
services:
  - postgresql
  - redis-server
before_script:
  - psql -c "CREATE DATABASE ase_acecard_test_database;" -U postgres
  - psql -c "CREATE USER acecard WITH PASSWORD 'acecard';" -U postgres
